# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('img', models.ImageField(upload_to='Classification/img')),
            ],
        ),
    ]
