# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classification.Classification')),
            ],
        ),
    ]
