# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Tag/img'),
        ),
        migrations.AddField(
            model_name='tag',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
